version: "2.3"

networks:
  ros-network:
    driver: bridge

services:
  roscore:
    image: ros:kinetic
    command: roscore
    networks:
      - ros-network
    
  rviz:
    image: carlowiesse/rviz:kinetic
    # command: ["/bin/sh", "-c", "glxinfo -v | grep OpenGL"] # Check renderer (GPU or CPU)
    depends_on:
      - roscore
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://roscore:11311
    networks:
      - ros-network